# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {5}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {6}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.cache/wt [current_project]
set_property parent.project_path C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/baud_gen.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/chu_gpi.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/chu_gpo.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/chu_mcs_bridge.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/chu_mmio_controller.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/include/chu_pkg.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/chu_timer.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/chu_uart.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/fifo.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/fifo_ctrl.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/mmio_sys_vanilla.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/register_file.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/uart.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/uart_rx.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/uart_tx.sv
  C:/FPGA_PROTOTYPING/Microblaze/hardware/src/mcs_top_vanilla.sv
}
read_verilog -library xil_defaultlib {
  C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/clock/hdl/clock_wrapper.v
  C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/hdl/cpu_wrapper.v
}
add_files C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/cpu.bd
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_de6f_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_de6f_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_de6f_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_de6f_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/bd_de6f_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/cpu_ooc.xdc]

add_files C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/clock/clock.bd
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/clock/clock_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA_PROTOTYPING/Microblaze/hardware/constraints.xdc
set_property used_in_implementation false [get_files C:/FPGA_PROTOTYPING/Microblaze/hardware/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top mcs_top_vanilla -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mcs_top_vanilla.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mcs_top_vanilla_utilization_synth.rpt -pb mcs_top_vanilla_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
