# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0.xci
# IP: The module: 'cpu_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/bd_de6f.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f || ORIG_REF_NAME==bd_de6f} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_microblaze_I_0 || ORIG_REF_NAME==bd_de6f_microblaze_I_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_rst_0_0 || ORIG_REF_NAME==bd_de6f_rst_0_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_de6f_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_ilmb_0 || ORIG_REF_NAME==bd_de6f_ilmb_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_de6f_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_dlmb_0 || ORIG_REF_NAME==bd_de6f_dlmb_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_de6f_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_de6f_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_de6f_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_de6f_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_de6f_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_lmb_bram_I_0 || ORIG_REF_NAME==bd_de6f_lmb_bram_I_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_mdm_0_0 || ORIG_REF_NAME==bd_de6f_mdm_0_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_8/bd_de6f_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_xlconcat_0_0 || ORIG_REF_NAME==bd_de6f_xlconcat_0_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_de6f_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_iomodule_0_0 || ORIG_REF_NAME==bd_de6f_iomodule_0_0} -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_microblaze_I_0 || ORIG_REF_NAME==bd_de6f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0_ooc_debug.xdc

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_rst_0_0 || ORIG_REF_NAME==bd_de6f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_rst_0_0 || ORIG_REF_NAME==bd_de6f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_de6f_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_ilmb_0 || ORIG_REF_NAME==bd_de6f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_de6f_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_dlmb_0 || ORIG_REF_NAME==bd_de6f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_de6f_lmb_bram_I_0_ooc.xdc

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_mdm_0_0 || ORIG_REF_NAME==bd_de6f_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0_ooc_trace.xdc

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_de6f_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_iomodule_0_0 || ORIG_REF_NAME==bd_de6f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/bd_de6f_ooc.xdc

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0.xci
# IP: The module: 'cpu_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/bd_de6f.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f || ORIG_REF_NAME==bd_de6f} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_microblaze_I_0 || ORIG_REF_NAME==bd_de6f_microblaze_I_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_rst_0_0 || ORIG_REF_NAME==bd_de6f_rst_0_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_de6f_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_ilmb_0 || ORIG_REF_NAME==bd_de6f_ilmb_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_de6f_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_dlmb_0 || ORIG_REF_NAME==bd_de6f_dlmb_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_de6f_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_de6f_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_de6f_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_de6f_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_de6f_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_lmb_bram_I_0 || ORIG_REF_NAME==bd_de6f_lmb_bram_I_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_mdm_0_0 || ORIG_REF_NAME==bd_de6f_mdm_0_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_8/bd_de6f_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_xlconcat_0_0 || ORIG_REF_NAME==bd_de6f_xlconcat_0_0} -quiet] -quiet

# IP: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_de6f_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_de6f_iomodule_0_0 || ORIG_REF_NAME==bd_de6f_iomodule_0_0} -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_microblaze_I_0 || ORIG_REF_NAME==bd_de6f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_de6f_microblaze_I_0_ooc_debug.xdc

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_rst_0_0 || ORIG_REF_NAME==bd_de6f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_de6f_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_rst_0_0 || ORIG_REF_NAME==bd_de6f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_de6f_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_ilmb_0 || ORIG_REF_NAME==bd_de6f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_de6f_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_dlmb_0 || ORIG_REF_NAME==bd_de6f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_de6f_lmb_bram_I_0_ooc.xdc

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_mdm_0_0 || ORIG_REF_NAME==bd_de6f_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_de6f_mdm_0_0_ooc_trace.xdc

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_de6f_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_de6f_iomodule_0_0 || ORIG_REF_NAME==bd_de6f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FPGA_PROTOTYPING/Microblaze/uBlaze/ublaze_mcs/ublaze_mcs.srcs/sources_1/bd/cpu/ip/cpu_microblaze_mcs_0_0/bd_0/bd_de6f_ooc.xdc
