# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/123/OneDrive/Desktop/FPGA_PROTOTYPING_IN_SV/Microblaze/hardware/constraints.xdc

# Block Designs: bd/uBlaze_MCS/uBlaze_MCS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_MCS || ORIG_REF_NAME==uBlaze_MCS} -quiet] -quiet

# IP: bd/uBlaze_MCS/ip/uBlaze_MCS_microblaze_mcs_0_0/uBlaze_MCS_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uBlaze_MCS_microblaze_mcs_0_0 || ORIG_REF_NAME==uBlaze_MCS_microblaze_mcs_0_0} -quiet] -quiet

# Block Designs: bd/clock_ip/clock_ip.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_ip || ORIG_REF_NAME==clock_ip} -quiet] -quiet

# IP: bd/clock_ip/ip/clock_ip_clk_wiz_0_0/clock_ip_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_ip_clk_wiz_0_0 || ORIG_REF_NAME==clock_ip_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/uBlaze_MCS/uBlaze_MCS_ooc.xdc

# XDC: bd/clock_ip/clock_ip_ooc.xdc
