set_property CFGBVS VCCO [current_design] 
set_property CONFIG_VOLTAGE 3.3 [current_design] 
set_property BITSTREAM.GENERAL.COMPRESS true [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 

set_property -dict {PACKAGE_PIN R4 IOSTANDARD DIFF_SSTL15} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD DIFF_SSTL15} [get_ports sys_clk_n] 

set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports sys_rstn] 

set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {seg_sel[0]}] 
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {seg_sel[1]}] 
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {seg_sel[2]}] 
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {seg_sel[3]}] 
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {seg_sel[4]}] 
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {seg_sel[5]}] 
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {seg_sel[6]}] 
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {seg_sel[7]}] 

set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports {seg_led1[0]}] 
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports {seg_led1[1]}] 
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports {seg_led1[2]}] 
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {seg_led1[3]}] 
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {seg_led1[4]}] 
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports {seg_led1[5]}] 
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {seg_led1[6]}] 
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports {seg_led1[7]}]

set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {seg_led2[0]}] 
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {seg_led2[1]}] 
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports {seg_led2[2]}] 
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports {seg_led2[3]}] 
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports {seg_led2[4]}] 
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports {seg_led2[5]}] 
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {seg_led2[6]}] 
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {seg_led2[7]}] 

set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports clr] 
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports cnt_en] 

set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {duty_cycle[0]}] 
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {duty_cycle[1]}] 
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {duty_cycle[2]}] 
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {duty_cycle[3]}] 