# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FPGA_PROTOTYPING/uBlaze_mmio_ss/hardware/constraints.xdc

# Block Designs: bd/cpu/cpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu || ORIG_REF_NAME==cpu} -quiet] -quiet

# IP: bd/cpu/ip/cpu_microblaze_mcs_0_0/cpu_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_microblaze_mcs_0_0 || ORIG_REF_NAME==cpu_microblaze_mcs_0_0} -quiet] -quiet

# Block Designs: bd/clock/clock.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] -quiet

# IP: bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_clk_wiz_0_0 || ORIG_REF_NAME==clock_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/cpu/cpu_ooc.xdc

# XDC: bd/clock/clock_ooc.xdc
